#!/usr/bin/env sh

echo 'docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$GIT_SHA1 -t $IMAGE_NAME .'
echo "date = `date -u +'%Y-%m-%dT%H:%M:%SZ'"
echo "GIT_SHA1 = $GIT_SHA1"
echo "IMAGE_NAME = $IMAGE_NAME"

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=$GIT_SHA1 -t $IMAGE_NAME .